version: '3.5'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=dunice_db
      - POSTGRES_USER=dunice_user
      - POSTGRES_PASSWORD=dunice_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  redis:
#    image: redis:buster
#    restart: always
#    container_name: redis_telemed
#    ports:
#      - 6379:6379
volumes:
  pgdata: