version: '3.5'

services:
  db:
    container_name: db_2
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=dunice_db
      - POSTGRES_USER=dunice_user
      - POSTGRES_PASSWORD=dunice_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  web:
    build: .
    restart: always
    volumes:
      - .:/telemed
      - /usr/share/nginx/html/static:/telemed/staticfiles
      - /usr/share/nginx/html/mediafiles:/telemed/mediafiles
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8000:8000 # Django
    env_file:
      - envs/.env
    depends_on:
      - db

volumes:
  pgdata: