# Generated by Django 3.2.6 on 2021-10-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0004_auto_20211008_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reply',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Ответ на вопрос'),
        ),
    ]
