# Generated by Django 3.2.6 on 2021-10-09 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0005_answer_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='negative_decision_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negative_decision_question', to='throwbox_app.answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='positive_decision_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positive_decision_question', to='throwbox_app.answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='questions',
            field=models.ManyToManyField(blank=True, to='throwbox_app.Question', verbose_name='Вопросы'),
        ),
    ]
