# Generated by Django 3.2.6 on 2021-10-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0006_auto_20211009_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
