# Generated by Django 3.2.6 on 2021-10-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0007_remove_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024, verbose_name='Текст события')),
                ('money_qty', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, to='throwbox_app.Event', verbose_name='События'),
        ),
    ]
