# Generated by Django 3.2.6 on 2021-10-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0008_auto_20211009_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money_qty',
            field=models.IntegerField(default=1000),
        ),
    ]
