# Generated by Django 3.2.6 on 2021-10-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0009_user_money_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='days_before_payday',
            field=models.IntegerField(default=10),
        ),
    ]
