# Generated by Django 3.2.6 on 2021-10-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0010_user_days_before_payday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inflation_koeff',
            field=models.FloatField(default=1),
        ),
    ]
