# Generated by Django 3.2.6 on 2021-10-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0011_user_inflation_koeff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='negative_decision_question',
            new_name='negative_decision_answer',
        ),
    ]
