# Generated by Django 3.2.6 on 2021-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0012_rename_negative_decision_question_question_negative_decision_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reply',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Текст помощника'),
        ),
    ]
