# Generated by Django 3.2.6 on 2021-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0013_alter_answer_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_text',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='warn_about_wrong_decision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='warning_text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
