# Generated by Django 3.2.6 on 2021-10-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throwbox_app', '0016_answer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='links',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
